---
- name: "[RedHat] Add the Google Stackdriver monitoring yum repository."
  yum_repository:
    name: google-cloud-monitoring
    baseurl: "{{ stackdriver_monitoring_repo }}-$basearch"
    description: A google repo that contains monitoring stuff
    gpgkey: "{{ gpgkeys }}"
    gpgcheck: yes
    enabled: yes
    repo_gpgcheck: yes

- name: "[RedHat] Add the Google Stackdriver logging yum repository."
  yum_repository:
    name: google-cloud-logging
    baseurl: "{{ stackdriver_logging_repo }}-$basearch"
    description: A google repo that contains logging stuff
    gpgkey: "{{ gpgkeys }}"
    gpgcheck: yes
    enabled: yes
    repo_gpgcheck: yes

- name: "[RedHat] Install the Stackdriver agent."
  yum:
    name: "{{ stackdriver_collectd_package }}"
    state: present
  notify: restart stackdriver

- name: adding stackdriver configs
  template:
    src: stackdriver.sysconfig
    dest: "{{ stackdriver_sysconfig }}"
    backup: yes

- name: "[RedHat] restart-stackdriver-agent"
  systemd:
    state: started
    daemon_reload: yes
    name: "{{ stackdriver_collectd_service }}"
    enabled: yes
