---
- name: "[RedHat] Add the Google Stackdriver monitoring yum repository."
  yum_repository:
    name: google-cloud-monitoring
    baseurl: "{{ stackdriver_monitoring_repo }}-$basearch"
    description: A google repo that contains monitoring stuff
    gpgkey: "{{ gpgkeys }}"
    gpgcheck: yes
    enabled: yes
    repo_gpgcheck: yes

- name: "[RedHat] Add the Google Stackdriver logging yum repository."
  yum_repository:
    name: google-cloud-logging
    baseurl: "{{ stackdriver_logging_repo }}-$basearch"
    description: A google repo that contains logging stuff
    gpgkey: "{{ gpgkeys }}"
    gpgcheck: yes
    enabled: yes
    repo_gpgcheck: yes

- name: "[RedHat] Yum installing {{ packages }}"
  yum:
    name: "{{ packages }}"
    state: present

- name: [RedHat] adding stackdriver configs
  template:
    src: stackdriver.sysconfig
    dest: "{{ stackdriver_sysconfig }}"
    backup: yes

- name: "[RedHat] Starting service {{ services }}"
  systemd:
    state: started
    daemon_reload: yes
    name: "{{ services }}"
    enabled: yes
